version: "2.1"

services:
  a9s-sample-mongodb-app:
    image: avarteqgmbh/a9s-sample-mongodb-app
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://anynines:password@mongo:27017/mongodb
      MONGODB_DATABASE: mongodb
  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongodb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
